name: Go Build and Test

on:
  push:
    branches:
      - master
    paths:
      - '**/*.go'
  pull_request:
    paths:
      - '**/*.go'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Run tests with coverage
        run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Print coverage result
        if: success()
        run: go tool cover -func=coverage.out
